#ifndef _TIMER_DEVICE_H_INCLUDED_
#define _TIMER_DEVICE_H_INCLUDED_

#include <linux/ioctl.h>

#define DEVICE_NAME "dev_driver"
#define DEVICE_MAJOR_NUMBER 242

#define IOCTL_SET_OPTION _IOW(DEVICE_MAJOR_NUMBER, 0, char*)
#define IOCTL_COMMAND _IO(DEVICE_MAJOR_NUMBER, 0)

#endif /* _TIMER_DEVICE_H_INCLUDED_ */
