/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hangman_MainActivity_InputThread */

#ifndef _Included_com_example_hangman_MainActivity_InputThread
#define _Included_com_example_hangman_MainActivity_InputThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_hangman_MainActivity_InputThread_MIN_PRIORITY
#define com_example_hangman_MainActivity_InputThread_MIN_PRIORITY 1L
#undef com_example_hangman_MainActivity_InputThread_NORM_PRIORITY
#define com_example_hangman_MainActivity_InputThread_NORM_PRIORITY 5L
#undef com_example_hangman_MainActivity_InputThread_MAX_PRIORITY
#define com_example_hangman_MainActivity_InputThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
