/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hangman_MainActivity_Payload */

#ifndef _Included_com_example_hangman_MainActivity_Payload
#define _Included_com_example_hangman_MainActivity_Payload
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
