/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_NDKExam */

#ifndef _Included_org_example_ndk_NDKExam
#define _Included_org_example_ndk_NDKExam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_NDKExam
 * Method:    product
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_NDKExam_product
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_example_ndk_NDKExam
 * Method:    testString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_NDKExam_testString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
